name: Stackoverflow-Stats-CI 
on:
  pull_request:
    branches: [ master ]
  schedule:
    # Runs 1:00 hours
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest stackoverflow stats

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      # Fetch the details from stackoverflow
      # Badges, Reputation and Activities in Stackoverflow
      - name: Fetch Stackoverflow stats details
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          gh_token: ${{ secrets.README_TOKEN }}
          feed_list: "https://stackoverflow.com/feeds/user/8854824"
